version: '3.8'

services:
  scraper-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - PORT=8000
      - HOST=0.0.0.0
      - USE_UNDETECTED_CHROME=${USE_UNDETECTED_CHROME:-true}
      - PROXY_LIST=${PROXY_LIST:-}
      - PROXY_USERNAME=${PROXY_USERNAME:-}
      - PROXY_PASSWORD=${PROXY_PASSWORD:-}
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
    volumes:
      - /tmp/chrome-user-data:/tmp/chrome-user-data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - scraper-api
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    driver: bridge